### ISSUE TITLE
dependencies in NVIDIA GeForce RTX 3090 GPU

### ISSUE THREAD

**Issue by BuyiZhu** [michaeltrs/DeepSatModels#10]
Thank you for your amazing job and open-source code.
However, I encountered an issue when installing dependencies on the **NVIDIA GeForce RTX 3090 GPU**. 
Specifically, the 3090 does not support cudatoolkit versions below 11.0. As a result, I attempted to install a higher version of cudatoolkit  and its corresponding pytorch, but it led to conflicts with other dependencies. 
Could you please provide a deepsatmodels_env.yml suitable for a higher cudatoolkit version?

**Comment by zkjisj** [comment]
RTX3090 supports cudatoolkit11.1, I suggest you install pytorch and cuda first, then run the code to solve other environment questions.

**Comment by zkjisj** [comment]
Here is an environment for reference.
name: deepsatmodels
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - cloudpickle=1.5.0=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cython=0.29.21=py38h950e882_0
  - cytoolz=0.10.1=py38h516909a_0
  - dask-core=2.21.0=py_0
  - decorator=4.4.2=py_0
  - enum34=1.1.10=py38h32f6830_1
  - freetype=2.10.2=h5ab3b9f_0
  - imagecodecs-lite=2019.12.3=py38h8790de6_1
  - imageio=2.9.0=py_0
  - intel-openmp=2020.1=217
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py38hbf85e49_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py38h91b0d89_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.9.0=py38hfd86e86_0
  - numpy=1.18.5=py38ha1c710e_0
  - numpy-base=1.18.5=py38hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_1
  - pandas=1.0.5=py38h0573a6f_0
  - pathlib=1.0.1=py38h32f6830_2
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.1.1=py38_1
  - pycocotools=2.0.1=py38h1e0a361_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.3=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py38h8790de6_1
  - pyyaml=5.3.1=py38h1e0a361_0
  - readline=8.0=h7b6447c_0
  - scikit-image=0.17.2=py38hcb8c335_1
  - scikit-learn=0.23.1=py38h423224d_0
  - setuptools=49.2.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2019.7.26.2=py38_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h1e0a361_1
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - addict==2.2.1
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chainer==7.7.0
    - chainercv==0.13.1
    - chardet==3.0.4
    - dataclasses==0.6
    - fcn==6.4.17
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - gdown==3.12.2
    - google-auth==1.19.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - h5py==2.10.0
    - idna==2.10
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - mmcv==1.1.2
    - nibabel==3.1.1
    - oauthlib==3.1.0
    - opencv-python==4.4.0.42
    - opt-einsum==3.3.0
    - packaging==20.4
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pypng==0.0.20
    - pysocks==1.7.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.4.1
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - torchfcn==1.9.6
    - tqdm==4.48.0
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yapf==0.30.0
    - einops==0.3.2

**Comment by zkjisj** [comment]
This environment can run the code segmentation_training.py, however encounter some question related to the edition of keras when run the code segmentation_training_transf.py

**Comment by BuyiZhu** [comment]
Thanks, @zkjisj , I try but still meet many conflicts in RTX3090. I finally do my exp in 2080.
