### ISSUE TITLE
Confusion about PASTIS-24 dataset

### ISSUE THREAD

**Issue by zkjisj** [michaeltrs/DeepSatModels#11]
As the title, it seems to that you forget to set the model_input_fn for model 'TSViT', I fixed it to use the function bidir_segmentation_inputs(sample, device). The PASTIS-24 dataset you present have 11 channels, while the initial PASTIS data just has 10 channels, where does the extra 1 channel come from?

**Comment by BuyiZhu** [comment]
Regarding the additional channel, you can refer to the function TileDates under data/PASTIS24/data_transforms.py.
```
def __call__(self, sample):
    doy = self.repeat(sample['doy'], binned=self.doy_bins is not None)
    sample['inputs'] = torch.cat((sample['inputs'], doy), dim=1)
    del sample['doy']
    return sample
```
It encodes the timestamps of the images into one channel and concatenates it with the original data.

**Comment by zkjisj** [comment]
Thanks for your reply, I have one more question that the initial patch size in PASTIS is 128*128, it isn't divisible by 24 (the used patch size in the literature). How were each samples processed?

**Comment by zkjisj** [comment]
I'm sorry for uncarefully reading, I found the processing method in the code.
