### ISSUE TITLE
failed, network error in downloading PASTIS24 data

### ISSUE THREAD

**Issue by June01** [michaeltrs/DeepSatModels#2]
Hi, thanks for your hard work on this project. 

When I try to download the [PASTIS24](https://drive.google.com/file/d/1Av9hou8DviCJsEB9a_XU9SyqTuNxVpdE/view?usp=share_link) from google drive, I kept facing the network error in the middle of downloading. This issue applies to other browsers, accounts, computers as well from what I can try. So I am wondering would you please try to upload it again or maybe share a google drive folder so that in worst case I could still download one by one? Any quick response is very much appreciated.

**Comment by June01** [comment]
Btw, I found no pre-trained models in this link - the [pre-trained models and tensorboard files](https://drive.google.com/file/d/1AzWEtHxojuCjaIsekja4J54LuEb9e7kw/view?usp=share_link). Should any pre-trained models been uploaded as well?

**Comment by michaeltrs** [comment]
Hi @June01, thanks for pointing this out. I have uploaded the [PASTIS24 in parts](https://drive.google.com/drive/folders/1Lm0repzD_1NVcECsrwF8Q3bP2XEp2a0y?usp=sharing), I hope this helps with download issues.  After downloading you can combine all files together and unzip.
```bash
zip -F PASTIS24_25part.zip --out PASTIS24.zip
unzip PASTIS24.zip -d .
```

**Comment by BastianChen** [comment]
> Hi @June01, thanks for pointing this out. I have uploaded the [PASTIS24 in parts](https://drive.google.com/drive/folders/1Lm0repzD_1NVcECsrwF8Q3bP2XEp2a0y?usp=sharing), I hope this helps with download issues. After downloading you can combine all files together and unzip.
> 
> ```shell
> zip -F PASTIS24_25part.zip --out PASTIS24.zip
> unzip PASTIS24.zip -d .
> ```

Hi, I am very interested in this project.
According to this link, I successfully downloaded the dataset, but there is only pickle24x24 in the dataset. I can't find fold-paths. So when I run this project，will occur FileNotFoundError. Could you help me solve this problem？Thanks.

**Comment by michaeltrs** [comment]
> > Hi @June01, thanks for pointing this out. I have uploaded the [PASTIS24 in parts](https://drive.google.com/drive/folders/1Lm0repzD_1NVcECsrwF8Q3bP2XEp2a0y?usp=sharing), I hope this helps with download issues. After downloading you can combine all files together and unzip.
> > ```shell
> > zip -F PASTIS24_25part.zip --out PASTIS24.zip
> > unzip PASTIS24.zip -d .
> > ```
> 
> Hi, I am very interested in this project. According to this link, I successfully downloaded the dataset, but there is only pickle24x24 in the dataset. I can't find fold-paths. So when I run this project，will occur FileNotFoundError. Could you help me solve this problem？Thanks.

@CChBen are you still having trouble getting the fold-paths? I just downloaded the data and everything seems to be there

**Comment by BastianChen** [comment]
> > > Hi @June01, thanks for pointing this out. I have uploaded the [PASTIS24 in parts](https://drive.google.com/drive/folders/1Lm0repzD_1NVcECsrwF8Q3bP2XEp2a0y?usp=sharing), I hope this helps with download issues. After downloading you can combine all files together and unzip.
> > > ```shell
> > > zip -F PASTIS24_25part.zip --out PASTIS24.zip
> > > unzip PASTIS24.zip -d .
> > > ```
> > 
> > 
> > Hi, I am very interested in this project. According to this link, I successfully downloaded the dataset, but there is only pickle24x24 in the dataset. I can't find fold-paths. So when I run this project，will occur FileNotFoundError. Could you help me solve this problem？Thanks.
> 
> @CChBen are you still having trouble getting the fold-paths? I just downloaded the data and everything seems to be there

Hi @michaeltrs, I believe that the files in the fold-paths directory are used to store the paths of files in Pickle24x24. Therefore, I wrote a code to generate these files myself.

**Comment by michaeltrs** [comment]
@CChBen that is correct. You will need the same folds if you want to compare your results with our paper or [Garnot 2021](https://openaccess.thecvf.com/content/ICCV2021/html/Garnot_Panoptic_Segmentation_of_Satellite_Image_Time_Series_With_Convolutional_Temporal_ICCV_2021_paper.html) (same paths). Let me investigate what is the issue with the data, in the meantime I have uploaded the [folds as a separate file to download](https://drive.google.com/file/d/1xZv1YPh-7yZJgXSlmMH-HdAq1DaaLM0S/view?usp=sharing).
