### ISSUE TITLE
A question about eq.1 in paper

### ISSUE THREAD

**Issue by zhangda1018** [michaeltrs/DeepSatModels#9]
Hi,
Nice work first!
But I'm sorry to ask the dimension of R in eq.1 in paper.
![image](https://github.com/michaeltrs/DeepSatModels/assets/66893156/47b2e4de-1d1f-4780-b7f7-58f19750c9a4)
Does this R∈N+1×d mean R∈(N+1)×d ? Beacuse this makes me confused.
Thanks!

**Comment by michaeltrs** [comment]
Hi, yes, it is as you suggest, N+1 tokens of size d
